-- generated by scripts/generate-timetable-preset-seed.sh
-- source of truth: supabase/seeds/timetable_presets_top_universities.csv

insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
values (
  null,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"09:00","end_time":"10:40"},{"period":2,"label":"2限","start_time":"10:45","end_time":"12:25"},{"period":3,"label":"3限","start_time":"13:10","end_time":"14:50"},{"period":4,"label":"4限","start_time":"14:55","end_time":"16:35"},{"period":5,"label":"5限","start_time":"16:40","end_time":"18:20"},{"period":6,"label":"6限","start_time":"18:25","end_time":"20:05"},{"period":7,"label":"7限","start_time":"20:10","end_time":"21:50"}]'::jsonb,
  true
)
on conflict (name) where university_id is null
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

do $$
declare
  preset record;
  target_university_id uuid;
begin
  for preset in
    select *
    from jsonb_to_recordset(
      '[
        {"university_name":"専修大学","weekdays_csv":"1,2,3,4,5","periods":[{"period":1,"label":"1限","start_time":"09:00","end_time":"10:30"},{"period":2,"label":"2限","start_time":"10:45","end_time":"12:15"},{"period":3,"label":"3限","start_time":"13:05","end_time":"14:35"},{"period":4,"label":"4限","start_time":"14:50","end_time":"16:20"},{"period":5,"label":"5限","start_time":"16:35","end_time":"18:05"},{"period":6,"label":"6限","start_time":"18:15","end_time":"19:45"},{"period":7,"label":"7限","start_time":"19:55","end_time":"21:25"}]},
        {"university_name":"明治大学","weekdays_csv":"1,2,3,4,5","periods":[{"period":1,"label":"1限","start_time":"09:00","end_time":"10:40"},{"period":2,"label":"2限","start_time":"10:50","end_time":"12:30"},{"period":3,"label":"3限","start_time":"13:30","end_time":"15:10"},{"period":4,"label":"4限","start_time":"15:20","end_time":"17:00"},{"period":5,"label":"5限","start_time":"17:10","end_time":"18:50"},{"period":6,"label":"6限","start_time":"19:00","end_time":"20:40"}]},
        {"university_name":"早稲田大学","weekdays_csv":"1,2,3,4,5","periods":[{"period":1,"label":"1限","start_time":"08:50","end_time":"10:30"},{"period":2,"label":"2限","start_time":"10:40","end_time":"12:20"},{"period":3,"label":"3限","start_time":"13:10","end_time":"14:50"},{"period":4,"label":"4限","start_time":"15:05","end_time":"16:45"},{"period":5,"label":"5限","start_time":"17:00","end_time":"18:40"},{"period":6,"label":"6限","start_time":"18:55","end_time":"20:35"}]},
        {"university_name":"慶應義塾大学","weekdays_csv":"1,2,3,4,5","periods":[{"period":1,"label":"1限","start_time":"09:00","end_time":"10:30"},{"period":2,"label":"2限","start_time":"10:45","end_time":"12:15"},{"period":3,"label":"3限","start_time":"13:00","end_time":"14:30"},{"period":4,"label":"4限","start_time":"14:45","end_time":"16:15"},{"period":5,"label":"5限","start_time":"16:30","end_time":"18:00"},{"period":6,"label":"6限","start_time":"18:10","end_time":"19:40"},{"period":7,"label":"7限","start_time":"19:50","end_time":"21:20"}]},
        {"university_name":"東京大学","weekdays_csv":"1,2,3,4,5","periods":[{"period":1,"label":"1限","start_time":"08:30","end_time":"10:15"},{"period":2,"label":"2限","start_time":"10:25","end_time":"12:10"},{"period":3,"label":"3限","start_time":"13:00","end_time":"14:45"},{"period":4,"label":"4限","start_time":"14:55","end_time":"16:40"},{"period":5,"label":"5限","start_time":"16:50","end_time":"18:35"},{"period":6,"label":"6限","start_time":"18:45","end_time":"20:30"}]},
        {"university_name":"京都大学","weekdays_csv":"1,2,3,4,5","periods":[{"period":1,"label":"1限","start_time":"08:45","end_time":"10:15"},{"period":2,"label":"2限","start_time":"10:30","end_time":"12:00"},{"period":3,"label":"3限","start_time":"13:15","end_time":"14:45"},{"period":4,"label":"4限","start_time":"15:00","end_time":"16:30"},{"period":5,"label":"5限","start_time":"16:45","end_time":"18:15"}]},
        {"university_name":"大阪大学","weekdays_csv":"1,2,3,4,5","periods":[{"period":1,"label":"1限","start_time":"08:50","end_time":"10:20"},{"period":2,"label":"2限","start_time":"10:30","end_time":"12:00"},{"period":3,"label":"3限","start_time":"13:30","end_time":"15:00"},{"period":4,"label":"4限","start_time":"15:10","end_time":"16:40"},{"period":5,"label":"5限","start_time":"16:50","end_time":"18:20"},{"period":6,"label":"6限","start_time":"18:30","end_time":"20:00"}]},
        {"university_name":"北海道大学","weekdays_csv":"1,2,3,4,5","periods":[{"period":1,"label":"1限","start_time":"08:45","end_time":"10:15"},{"period":2,"label":"2限","start_time":"10:30","end_time":"12:00"},{"period":3,"label":"3限","start_time":"13:00","end_time":"14:30"},{"period":4,"label":"4限","start_time":"14:45","end_time":"16:15"},{"period":5,"label":"5限","start_time":"16:30","end_time":"18:00"},{"period":6,"label":"6限","start_time":"18:15","end_time":"19:45"}]},
        {"university_name":"東北大学","weekdays_csv":"1,2,3,4,5","periods":[{"period":1,"label":"1限","start_time":"08:50","end_time":"10:20"},{"period":2,"label":"2限","start_time":"10:30","end_time":"12:00"},{"period":3,"label":"3限","start_time":"13:00","end_time":"14:30"},{"period":4,"label":"4限","start_time":"14:40","end_time":"16:10"},{"period":5,"label":"5限","start_time":"16:20","end_time":"17:50"}]},
        {"university_name":"名古屋大学","weekdays_csv":"1,2,3,4,5","periods":[{"period":1,"label":"1限","start_time":"08:45","end_time":"10:15"},{"period":2,"label":"2限","start_time":"10:30","end_time":"12:00"},{"period":3,"label":"3限","start_time":"13:00","end_time":"14:30"},{"period":4,"label":"4限","start_time":"14:45","end_time":"16:15"},{"period":5,"label":"5限","start_time":"16:30","end_time":"18:00"}]},
        {"university_name":"九州大学","weekdays_csv":"1,2,3,4,5","periods":[{"period":1,"label":"1限","start_time":"08:40","end_time":"10:10"},{"period":2,"label":"2限","start_time":"10:30","end_time":"12:00"},{"period":3,"label":"3限","start_time":"13:00","end_time":"14:30"},{"period":4,"label":"4限","start_time":"14:50","end_time":"16:20"},{"period":5,"label":"5限","start_time":"16:40","end_time":"18:10"},{"period":6,"label":"6限","start_time":"18:30","end_time":"20:00"}]},
        {"university_name":"神戸大学","weekdays_csv":"1,2,3,4,5","periods":[{"period":1,"label":"1限","start_time":"08:50","end_time":"10:20"},{"period":2,"label":"2限","start_time":"10:40","end_time":"12:10"},{"period":3,"label":"3限","start_time":"13:20","end_time":"14:50"},{"period":4,"label":"4限","start_time":"15:10","end_time":"16:40"},{"period":5,"label":"5限","start_time":"17:00","end_time":"18:30"},{"period":6,"label":"6限","start_time":"18:50","end_time":"20:20"}]},
        {"university_name":"筑波大学","weekdays_csv":"1,2,3,4,5","periods":[{"period":1,"label":"1限","start_time":"08:40","end_time":"09:55"},{"period":2,"label":"2限","start_time":"10:10","end_time":"11:25"},{"period":3,"label":"3限","start_time":"12:15","end_time":"13:30"},{"period":4,"label":"4限","start_time":"13:45","end_time":"15:00"},{"period":5,"label":"5限","start_time":"15:15","end_time":"16:30"},{"period":6,"label":"6限","start_time":"16:45","end_time":"18:00"},{"period":7,"label":"7限","start_time":"18:00","end_time":"19:15"}]},
        {"university_name":"横浜国立大学","weekdays_csv":"1,2,3,4,5","periods":[{"period":1,"label":"1限","start_time":"08:50","end_time":"10:20"},{"period":2,"label":"2限","start_time":"10:30","end_time":"12:00"},{"period":3,"label":"3限","start_time":"13:00","end_time":"14:30"},{"period":4,"label":"4限","start_time":"14:40","end_time":"16:10"},{"period":5,"label":"5限","start_time":"16:15","end_time":"17:45"},{"period":6,"label":"6限","start_time":"17:50","end_time":"19:20"},{"period":7,"label":"7限","start_time":"19:25","end_time":"20:55"}]},
        {"university_name":"千葉大学","weekdays_csv":"1,2,3,4,5","periods":[{"period":1,"label":"1限","start_time":"08:50","end_time":"10:20"},{"period":2,"label":"2限","start_time":"10:30","end_time":"12:00"},{"period":3,"label":"3限","start_time":"12:50","end_time":"14:20"},{"period":4,"label":"4限","start_time":"14:30","end_time":"16:00"},{"period":5,"label":"5限","start_time":"16:10","end_time":"17:40"}]},
        {"university_name":"広島大学","weekdays_csv":"1,2,3,4,5","periods":[{"period":1,"label":"1限","start_time":"08:45","end_time":"09:30"},{"period":2,"label":"2限","start_time":"09:30","end_time":"10:15"},{"period":3,"label":"3限","start_time":"10:30","end_time":"11:15"},{"period":4,"label":"4限","start_time":"11:15","end_time":"12:00"},{"period":5,"label":"5限","start_time":"12:50","end_time":"13:35"},{"period":6,"label":"6限","start_time":"13:35","end_time":"14:20"},{"period":7,"label":"7限","start_time":"14:35","end_time":"15:20"},{"period":8,"label":"8限","start_time":"15:20","end_time":"16:05"},{"period":9,"label":"9限","start_time":"16:20","end_time":"17:05"},{"period":10,"label":"10限","start_time":"17:05","end_time":"17:50"}]},
        {"university_name":"岡山大学","weekdays_csv":"1,2,3,4,5","periods":[{"period":1,"label":"1限","start_time":"08:40","end_time":"09:30"},{"period":2,"label":"2限","start_time":"09:40","end_time":"10:30"},{"period":3,"label":"3限","start_time":"10:45","end_time":"11:35"},{"period":4,"label":"4限","start_time":"11:45","end_time":"12:35"},{"period":5,"label":"5限","start_time":"13:25","end_time":"14:15"},{"period":6,"label":"6限","start_time":"14:25","end_time":"15:15"},{"period":7,"label":"7限","start_time":"15:30","end_time":"16:20"},{"period":8,"label":"8限","start_time":"16:30","end_time":"17:20"},{"period":9,"label":"9限","start_time":"17:30","end_time":"18:20"},{"period":10,"label":"10限","start_time":"18:30","end_time":"19:20"}]},
        {"university_name":"立命館大学","weekdays_csv":"1,2,3,4,5","periods":[{"period":1,"label":"1限","start_time":"09:00","end_time":"10:35"},{"period":2,"label":"2限","start_time":"10:45","end_time":"12:20"},{"period":3,"label":"3限","start_time":"13:10","end_time":"14:45"},{"period":4,"label":"4限","start_time":"14:55","end_time":"16:30"},{"period":5,"label":"5限","start_time":"16:40","end_time":"18:15"},{"period":6,"label":"6限","start_time":"18:25","end_time":"20:00"},{"period":7,"label":"7限","start_time":"20:10","end_time":"21:45"}]},
        {"university_name":"同志社大学","weekdays_csv":"1,2,3,4,5","periods":[{"period":1,"label":"1限","start_time":"09:00","end_time":"10:30"},{"period":2,"label":"2限","start_time":"10:45","end_time":"12:15"},{"period":3,"label":"3限","start_time":"13:10","end_time":"14:40"},{"period":4,"label":"4限","start_time":"14:55","end_time":"16:25"},{"period":5,"label":"5限","start_time":"16:40","end_time":"18:10"},{"period":6,"label":"6限","start_time":"18:25","end_time":"19:55"},{"period":7,"label":"7限","start_time":"20:10","end_time":"21:40"}]},
        {"university_name":"関西大学","weekdays_csv":"1,2,3,4,5","periods":[{"period":1,"label":"1限","start_time":"09:00","end_time":"10:30"},{"period":2,"label":"2限","start_time":"10:40","end_time":"12:10"},{"period":3,"label":"3限","start_time":"13:00","end_time":"14:30"},{"period":4,"label":"4限","start_time":"14:40","end_time":"16:10"},{"period":5,"label":"5限","start_time":"16:20","end_time":"17:50"},{"period":6,"label":"6限","start_time":"18:00","end_time":"19:30"},{"period":7,"label":"7限","start_time":"19:40","end_time":"21:10"}]},
        {"university_name":"関西学院大学","weekdays_csv":"1,2,3,4,5","periods":[{"period":1,"label":"1限","start_time":"08:50","end_time":"10:30"},{"period":2,"label":"2限","start_time":"11:00","end_time":"12:40"},{"period":3,"label":"3限","start_time":"13:20","end_time":"15:00"},{"period":4,"label":"4限","start_time":"15:10","end_time":"16:50"},{"period":5,"label":"5限","start_time":"17:00","end_time":"18:40"}]},
        {"university_name":"法政大学","weekdays_csv":"1,2,3,4,5","periods":[{"period":1,"label":"1限","start_time":"08:50","end_time":"10:30"},{"period":2,"label":"2限","start_time":"10:40","end_time":"12:20"},{"period":3,"label":"3限","start_time":"13:10","end_time":"14:50"},{"period":4,"label":"4限","start_time":"15:00","end_time":"16:40"},{"period":5,"label":"5限","start_time":"16:50","end_time":"18:30"},{"period":6,"label":"6限","start_time":"18:35","end_time":"20:15"},{"period":7,"label":"7限","start_time":"20:20","end_time":"22:00"}]},
        {"university_name":"中央大学","weekdays_csv":"1,2,3,4,5","periods":[{"period":1,"label":"1限","start_time":"09:00","end_time":"10:40"},{"period":2,"label":"2限","start_time":"10:50","end_time":"12:30"},{"period":3,"label":"3限","start_time":"13:20","end_time":"15:00"},{"period":4,"label":"4限","start_time":"15:10","end_time":"16:50"},{"period":5,"label":"5限","start_time":"17:00","end_time":"18:40"},{"period":6,"label":"6限","start_time":"18:50","end_time":"20:30"}]},
        {"university_name":"日本大学","weekdays_csv":"1,2,3,4,5","periods":[{"period":1,"label":"1限","start_time":"09:00","end_time":"10:40"},{"period":2,"label":"2限","start_time":"10:55","end_time":"12:35"},{"period":3,"label":"3限","start_time":"13:25","end_time":"15:05"},{"period":4,"label":"4限","start_time":"15:20","end_time":"17:00"},{"period":5,"label":"5限","start_time":"17:15","end_time":"18:55"},{"period":6,"label":"6限","start_time":"19:05","end_time":"20:45"}]},
        {"university_name":"青山学院大学","weekdays_csv":"1,2,3,4,5","periods":[{"period":1,"label":"1限","start_time":"09:00","end_time":"10:30"},{"period":2,"label":"2限","start_time":"11:00","end_time":"12:30"},{"period":3,"label":"3限","start_time":"13:20","end_time":"14:50"},{"period":4,"label":"4限","start_time":"15:05","end_time":"16:35"},{"period":5,"label":"5限","start_time":"16:50","end_time":"18:20"},{"period":6,"label":"6限","start_time":"18:30","end_time":"20:00"},{"period":7,"label":"7限","start_time":"20:10","end_time":"21:40"}]},
        {"university_name":"立教大学","weekdays_csv":"1,2,3,4,5","periods":[{"period":1,"label":"1限","start_time":"08:50","end_time":"10:30"},{"period":2,"label":"2限","start_time":"10:45","end_time":"12:25"},{"period":3,"label":"3限","start_time":"13:25","end_time":"15:05"},{"period":4,"label":"4限","start_time":"15:20","end_time":"17:00"},{"period":5,"label":"5限","start_time":"17:10","end_time":"18:50"},{"period":6,"label":"6限","start_time":"18:55","end_time":"20:35"}]}
      ]'::jsonb
    ) as source(university_name text, weekdays_csv text, periods jsonb)
  loop
    select id
      into target_university_id
    from public.universities
    where name = preset.university_name
    limit 1;

    if target_university_id is null then
      raise warning '[WARNING] University not found: "%". Skipping timetable preset.', preset.university_name;
      continue;
    end if;

    insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
    values (
      target_university_id,
      'default',
      string_to_array(preset.weekdays_csv, ',')::smallint[],
      preset.periods,
      true
    )
    on conflict (university_id, name)
    do update set
      weekdays = excluded.weekdays,
      periods = excluded.periods,
      is_active = true,
      updated_at = now();
  end loop;
end $$;
