#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 1 || $# -gt 2 ]]; then
  echo "Usage: $0 <input_csv> [output_sql]" >&2
  exit 1
fi
# 入力CSVから時間割プリセット名を抽出し、SQLのINSERT文を生成するスクリプト。
INPUT_CSV="$1"
OUTPUT_SQL="${2:-}"

if [[ ! -f "$INPUT_CSV" ]]; then
  echo "Input CSV not found: $INPUT_CSV" >&2
  exit 1
fi

generate_sql() {
  awk -F',' '
    function escape_sql(s,   t) {
      t = s
      gsub("'\''", "'\''""'\''""'\''", t)
      return t
    }

    NR == 1 { next }
    NF < 6 { next }

    {
      university = $1
      period = $2
      label = $3
      start_time = $4
      end_time = $5
      weekdays = $6

      if (!(university in seen)) {
        seen[university] = 1
        order[++count] = university
        weekdays_map[university] = weekdays
      }

      period_json = sprintf("{\"period\":%s,\"label\":\"%s\",\"start_time\":\"%s\",\"end_time\":\"%s\"}", period, label, start_time, end_time)

      if (periods_map[university] == "") {
        periods_map[university] = period_json
      } else {
        periods_map[university] = periods_map[university] "," period_json
      }
    }

    END {
      print "-- generated by scripts/generate-timetable-preset-seed.sh"
      print "-- source of truth: supabase/seeds/timetable_presets_top_universities.csv"
      print "\ninsert into public.timetable_presets (university_id, name, weekdays, periods, is_active)"
      print "values ("
      print "  null,"
      print "  '\''default'\'',"
      print "  array[1,2,3,4,5]::smallint[],"
      print "  '\''[{\"period\":1,\"label\":\"1限\",\"start_time\":\"09:00\",\"end_time\":\"10:40\"},{\"period\":2,\"label\":\"2限\",\"start_time\":\"10:45\",\"end_time\":\"12:25\"},{\"period\":3,\"label\":\"3限\",\"start_time\":\"13:10\",\"end_time\":\"14:50\"},{\"period\":4,\"label\":\"4限\",\"start_time\":\"14:55\",\"end_time\":\"16:35\"},{\"period\":5,\"label\":\"5限\",\"start_time\":\"16:40\",\"end_time\":\"18:20\"}]'\''::jsonb,"
      print "  true"
      print ")"
      print "on conflict (name) where university_id is null"
      print "do update set"
      print "  weekdays = excluded.weekdays,"
      print "  periods = excluded.periods,"
      print "  is_active = true,"
      print "  updated_at = now();\n"
      print "do $$"
      print "declare"
      print "  preset record;"
      print "  target_university_id uuid;"
      print "begin"
      print "  for preset in"
      print "    select *"
      print "    from jsonb_to_recordset("
      print "      '\''["

      for (i = 1; i <= count; i++) {
        university = order[i]
        weekdays_csv = weekdays_map[university]
        gsub("\\|", ",", weekdays_csv)
        escaped_university = escape_sql(university)
        suffix = (i < count) ? "," : ""
        print "        {\"university_name\":\"" escaped_university "\",\"weekdays_csv\":\"" weekdays_csv "\",\"periods\":[" periods_map[university] "]}" suffix
      }

      print "      ]'\''::jsonb"
      print "    ) as source(university_name text, weekdays_csv text, periods jsonb)"
      print "  loop"
      print "    select id"
      print "      into target_university_id"
      print "    from public.universities"
      print "    where name = preset.university_name"
      print "    limit 1;"
      print ""
      print "    if target_university_id is null then"
      print "      raise warning '\''[WARNING] University not found: \"%\". Skipping timetable preset.'\'', preset.university_name;"
      print "      continue;"
      print "    end if;"
      print ""
      print "    insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)"
      print "    values ("
      print "      target_university_id,"
      print "      '\''default'\'',"
      print "      string_to_array(preset.weekdays_csv, '\'','\'')::smallint[],"
      print "      preset.periods,"
      print "      true"
      print "    )"
      print "    on conflict (university_id, name)"
      print "    do update set"
      print "      weekdays = excluded.weekdays,"
      print "      periods = excluded.periods,"
      print "      is_active = true,"
      print "      updated_at = now();"
      print "  end loop;"
      print "end $$;"
    }
  ' "$INPUT_CSV"
}

if [[ -n "$OUTPUT_SQL" ]]; then
  generate_sql > "$OUTPUT_SQL"
  echo "Generated: $OUTPUT_SQL"
else
  generate_sql
fi
