-- generated by scripts/generate-timetable-preset-seed.sh
-- generated at 2026-03-04 11:52:02 UTC

insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
values (
  null,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"09:00","end_time":"10:40"},{"period":2,"label":"2限","start_time":"10:45","end_time":"12:25"},{"period":3,"label":"3限","start_time":"13:10","end_time":"14:50"},{"period":4,"label":"4限","start_time":"14:55","end_time":"16:35"},{"period":5,"label":"5限","start_time":"16:40","end_time":"18:20"}]'::jsonb,
  true
)
on conflict (name) where university_id is null
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

with upsert_university as (
  insert into public.universities (name)
  values ('専修大学')
  on conflict (name) do update set name = excluded.name
  returning id
), resolved_university as (
  select id from upsert_university
  union all
  select id from public.universities where name = '専修大学' limit 1
)
insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
select
  u.id,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"09:00","end_time":"10:40"},{"period":2,"label":"2限","start_time":"10:45","end_time":"12:25"},{"period":3,"label":"3限","start_time":"13:10","end_time":"14:50"},{"period":4,"label":"4限","start_time":"14:55","end_time":"16:35"},{"period":5,"label":"5限","start_time":"16:40","end_time":"18:20"}]'::jsonb,
  true
from resolved_university u
on conflict (university_id, name)
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

with upsert_university as (
  insert into public.universities (name)
  values ('明治大学')
  on conflict (name) do update set name = excluded.name
  returning id
), resolved_university as (
  select id from upsert_university
  union all
  select id from public.universities where name = '明治大学' limit 1
)
insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
select
  u.id,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"09:00","end_time":"10:40"},{"period":2,"label":"2限","start_time":"10:50","end_time":"12:30"},{"period":3,"label":"3限","start_time":"13:30","end_time":"15:10"},{"period":4,"label":"4限","start_time":"15:20","end_time":"17:00"},{"period":5,"label":"5限","start_time":"17:10","end_time":"18:50"}]'::jsonb,
  true
from resolved_university u
on conflict (university_id, name)
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

with upsert_university as (
  insert into public.universities (name)
  values ('早稲田大学')
  on conflict (name) do update set name = excluded.name
  returning id
), resolved_university as (
  select id from upsert_university
  union all
  select id from public.universities where name = '早稲田大学' limit 1
)
insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
select
  u.id,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"09:00","end_time":"10:30"},{"period":2,"label":"2限","start_time":"10:40","end_time":"12:10"},{"period":3,"label":"3限","start_time":"13:00","end_time":"14:30"},{"period":4,"label":"4限","start_time":"14:45","end_time":"16:15"},{"period":5,"label":"5限","start_time":"16:30","end_time":"18:00"}]'::jsonb,
  true
from resolved_university u
on conflict (university_id, name)
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

with upsert_university as (
  insert into public.universities (name)
  values ('慶應義塾大学')
  on conflict (name) do update set name = excluded.name
  returning id
), resolved_university as (
  select id from upsert_university
  union all
  select id from public.universities where name = '慶應義塾大学' limit 1
)
insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
select
  u.id,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"09:00","end_time":"10:30"},{"period":2,"label":"2限","start_time":"10:45","end_time":"12:15"},{"period":3,"label":"3限","start_time":"13:00","end_time":"14:30"},{"period":4,"label":"4限","start_time":"14:45","end_time":"16:15"},{"period":5,"label":"5限","start_time":"16:30","end_time":"18:00"}]'::jsonb,
  true
from resolved_university u
on conflict (university_id, name)
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

with upsert_university as (
  insert into public.universities (name)
  values ('東京大学')
  on conflict (name) do update set name = excluded.name
  returning id
), resolved_university as (
  select id from upsert_university
  union all
  select id from public.universities where name = '東京大学' limit 1
)
insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
select
  u.id,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"08:30","end_time":"10:15"},{"period":2,"label":"2限","start_time":"10:25","end_time":"12:10"},{"period":3,"label":"3限","start_time":"13:00","end_time":"14:45"},{"period":4,"label":"4限","start_time":"14:55","end_time":"16:40"},{"period":5,"label":"5限","start_time":"16:50","end_time":"18:35"}]'::jsonb,
  true
from resolved_university u
on conflict (university_id, name)
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

with upsert_university as (
  insert into public.universities (name)
  values ('京都大学')
  on conflict (name) do update set name = excluded.name
  returning id
), resolved_university as (
  select id from upsert_university
  union all
  select id from public.universities where name = '京都大学' limit 1
)
insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
select
  u.id,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"08:45","end_time":"10:15"},{"period":2,"label":"2限","start_time":"10:30","end_time":"12:00"},{"period":3,"label":"3限","start_time":"13:15","end_time":"14:45"},{"period":4,"label":"4限","start_time":"15:00","end_time":"16:30"},{"period":5,"label":"5限","start_time":"16:45","end_time":"18:15"}]'::jsonb,
  true
from resolved_university u
on conflict (university_id, name)
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

with upsert_university as (
  insert into public.universities (name)
  values ('大阪大学')
  on conflict (name) do update set name = excluded.name
  returning id
), resolved_university as (
  select id from upsert_university
  union all
  select id from public.universities where name = '大阪大学' limit 1
)
insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
select
  u.id,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"08:50","end_time":"10:20"},{"period":2,"label":"2限","start_time":"10:35","end_time":"12:05"},{"period":3,"label":"3限","start_time":"13:15","end_time":"14:45"},{"period":4,"label":"4限","start_time":"15:00","end_time":"16:30"},{"period":5,"label":"5限","start_time":"16:45","end_time":"18:15"}]'::jsonb,
  true
from resolved_university u
on conflict (university_id, name)
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

with upsert_university as (
  insert into public.universities (name)
  values ('北海道大学')
  on conflict (name) do update set name = excluded.name
  returning id
), resolved_university as (
  select id from upsert_university
  union all
  select id from public.universities where name = '北海道大学' limit 1
)
insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
select
  u.id,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"08:45","end_time":"10:15"},{"period":2,"label":"2限","start_time":"10:30","end_time":"12:00"},{"period":3,"label":"3限","start_time":"13:00","end_time":"14:30"},{"period":4,"label":"4限","start_time":"14:45","end_time":"16:15"},{"period":5,"label":"5限","start_time":"16:30","end_time":"18:00"}]'::jsonb,
  true
from resolved_university u
on conflict (university_id, name)
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

with upsert_university as (
  insert into public.universities (name)
  values ('東北大学')
  on conflict (name) do update set name = excluded.name
  returning id
), resolved_university as (
  select id from upsert_university
  union all
  select id from public.universities where name = '東北大学' limit 1
)
insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
select
  u.id,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"08:50","end_time":"10:20"},{"period":2,"label":"2限","start_time":"10:30","end_time":"12:00"},{"period":3,"label":"3限","start_time":"13:00","end_time":"14:30"},{"period":4,"label":"4限","start_time":"14:40","end_time":"16:10"},{"period":5,"label":"5限","start_time":"16:20","end_time":"17:50"}]'::jsonb,
  true
from resolved_university u
on conflict (university_id, name)
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

with upsert_university as (
  insert into public.universities (name)
  values ('名古屋大学')
  on conflict (name) do update set name = excluded.name
  returning id
), resolved_university as (
  select id from upsert_university
  union all
  select id from public.universities where name = '名古屋大学' limit 1
)
insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
select
  u.id,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"09:00","end_time":"10:30"},{"period":2,"label":"2限","start_time":"10:45","end_time":"12:15"},{"period":3,"label":"3限","start_time":"13:00","end_time":"14:30"},{"period":4,"label":"4限","start_time":"14:45","end_time":"16:15"},{"period":5,"label":"5限","start_time":"16:30","end_time":"18:00"}]'::jsonb,
  true
from resolved_university u
on conflict (university_id, name)
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

with upsert_university as (
  insert into public.universities (name)
  values ('九州大学')
  on conflict (name) do update set name = excluded.name
  returning id
), resolved_university as (
  select id from upsert_university
  union all
  select id from public.universities where name = '九州大学' limit 1
)
insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
select
  u.id,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"08:40","end_time":"10:10"},{"period":2,"label":"2限","start_time":"10:30","end_time":"12:00"},{"period":3,"label":"3限","start_time":"13:00","end_time":"14:30"},{"period":4,"label":"4限","start_time":"14:50","end_time":"16:20"},{"period":5,"label":"5限","start_time":"16:40","end_time":"18:10"}]'::jsonb,
  true
from resolved_university u
on conflict (university_id, name)
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

with upsert_university as (
  insert into public.universities (name)
  values ('神戸大学')
  on conflict (name) do update set name = excluded.name
  returning id
), resolved_university as (
  select id from upsert_university
  union all
  select id from public.universities where name = '神戸大学' limit 1
)
insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
select
  u.id,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"09:00","end_time":"10:30"},{"period":2,"label":"2限","start_time":"10:45","end_time":"12:15"},{"period":3,"label":"3限","start_time":"13:20","end_time":"14:50"},{"period":4,"label":"4限","start_time":"15:10","end_time":"16:40"},{"period":5,"label":"5限","start_time":"17:00","end_time":"18:30"}]'::jsonb,
  true
from resolved_university u
on conflict (university_id, name)
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

with upsert_university as (
  insert into public.universities (name)
  values ('筑波大学')
  on conflict (name) do update set name = excluded.name
  returning id
), resolved_university as (
  select id from upsert_university
  union all
  select id from public.universities where name = '筑波大学' limit 1
)
insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
select
  u.id,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"08:40","end_time":"10:10"},{"period":2,"label":"2限","start_time":"10:20","end_time":"11:50"},{"period":3,"label":"3限","start_time":"12:15","end_time":"13:45"},{"period":4,"label":"4限","start_time":"13:55","end_time":"15:25"},{"period":5,"label":"5限","start_time":"15:35","end_time":"17:05"}]'::jsonb,
  true
from resolved_university u
on conflict (university_id, name)
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

with upsert_university as (
  insert into public.universities (name)
  values ('横浜国立大学')
  on conflict (name) do update set name = excluded.name
  returning id
), resolved_university as (
  select id from upsert_university
  union all
  select id from public.universities where name = '横浜国立大学' limit 1
)
insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
select
  u.id,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"08:50","end_time":"10:20"},{"period":2,"label":"2限","start_time":"10:30","end_time":"12:00"},{"period":3,"label":"3限","start_time":"13:00","end_time":"14:30"},{"period":4,"label":"4限","start_time":"14:40","end_time":"16:10"},{"period":5,"label":"5限","start_time":"16:20","end_time":"17:50"}]'::jsonb,
  true
from resolved_university u
on conflict (university_id, name)
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

with upsert_university as (
  insert into public.universities (name)
  values ('千葉大学')
  on conflict (name) do update set name = excluded.name
  returning id
), resolved_university as (
  select id from upsert_university
  union all
  select id from public.universities where name = '千葉大学' limit 1
)
insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
select
  u.id,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"08:50","end_time":"10:20"},{"period":2,"label":"2限","start_time":"10:30","end_time":"12:00"},{"period":3,"label":"3限","start_time":"13:00","end_time":"14:30"},{"period":4,"label":"4限","start_time":"14:40","end_time":"16:10"},{"period":5,"label":"5限","start_time":"16:20","end_time":"17:50"}]'::jsonb,
  true
from resolved_university u
on conflict (university_id, name)
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

with upsert_university as (
  insert into public.universities (name)
  values ('広島大学')
  on conflict (name) do update set name = excluded.name
  returning id
), resolved_university as (
  select id from upsert_university
  union all
  select id from public.universities where name = '広島大学' limit 1
)
insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
select
  u.id,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"08:50","end_time":"10:20"},{"period":2,"label":"2限","start_time":"10:30","end_time":"12:00"},{"period":3,"label":"3限","start_time":"13:00","end_time":"14:30"},{"period":4,"label":"4限","start_time":"14:40","end_time":"16:10"},{"period":5,"label":"5限","start_time":"16:20","end_time":"17:50"}]'::jsonb,
  true
from resolved_university u
on conflict (university_id, name)
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

with upsert_university as (
  insert into public.universities (name)
  values ('岡山大学')
  on conflict (name) do update set name = excluded.name
  returning id
), resolved_university as (
  select id from upsert_university
  union all
  select id from public.universities where name = '岡山大学' limit 1
)
insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
select
  u.id,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"08:50","end_time":"10:20"},{"period":2,"label":"2限","start_time":"10:30","end_time":"12:00"},{"period":3,"label":"3限","start_time":"13:00","end_time":"14:30"},{"period":4,"label":"4限","start_time":"14:40","end_time":"16:10"},{"period":5,"label":"5限","start_time":"16:20","end_time":"17:50"}]'::jsonb,
  true
from resolved_university u
on conflict (university_id, name)
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

with upsert_university as (
  insert into public.universities (name)
  values ('立命館大学')
  on conflict (name) do update set name = excluded.name
  returning id
), resolved_university as (
  select id from upsert_university
  union all
  select id from public.universities where name = '立命館大学' limit 1
)
insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
select
  u.id,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"09:00","end_time":"10:40"},{"period":2,"label":"2限","start_time":"10:55","end_time":"12:35"},{"period":3,"label":"3限","start_time":"13:25","end_time":"15:05"},{"period":4,"label":"4限","start_time":"15:20","end_time":"17:00"},{"period":5,"label":"5限","start_time":"17:15","end_time":"18:55"}]'::jsonb,
  true
from resolved_university u
on conflict (university_id, name)
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

with upsert_university as (
  insert into public.universities (name)
  values ('同志社大学')
  on conflict (name) do update set name = excluded.name
  returning id
), resolved_university as (
  select id from upsert_university
  union all
  select id from public.universities where name = '同志社大学' limit 1
)
insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
select
  u.id,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"09:00","end_time":"10:30"},{"period":2,"label":"2限","start_time":"10:45","end_time":"12:15"},{"period":3,"label":"3限","start_time":"13:10","end_time":"14:40"},{"period":4,"label":"4限","start_time":"14:55","end_time":"16:25"},{"period":5,"label":"5限","start_time":"16:40","end_time":"18:10"}]'::jsonb,
  true
from resolved_university u
on conflict (university_id, name)
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

with upsert_university as (
  insert into public.universities (name)
  values ('関西大学')
  on conflict (name) do update set name = excluded.name
  returning id
), resolved_university as (
  select id from upsert_university
  union all
  select id from public.universities where name = '関西大学' limit 1
)
insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
select
  u.id,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"09:00","end_time":"10:40"},{"period":2,"label":"2限","start_time":"10:50","end_time":"12:30"},{"period":3,"label":"3限","start_time":"13:20","end_time":"15:00"},{"period":4,"label":"4限","start_time":"15:10","end_time":"16:50"},{"period":5,"label":"5限","start_time":"17:00","end_time":"18:40"}]'::jsonb,
  true
from resolved_university u
on conflict (university_id, name)
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

with upsert_university as (
  insert into public.universities (name)
  values ('関西学院大学')
  on conflict (name) do update set name = excluded.name
  returning id
), resolved_university as (
  select id from upsert_university
  union all
  select id from public.universities where name = '関西学院大学' limit 1
)
insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
select
  u.id,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"09:00","end_time":"10:40"},{"period":2,"label":"2限","start_time":"10:50","end_time":"12:30"},{"period":3,"label":"3限","start_time":"13:20","end_time":"15:00"},{"period":4,"label":"4限","start_time":"15:10","end_time":"16:50"},{"period":5,"label":"5限","start_time":"17:00","end_time":"18:40"}]'::jsonb,
  true
from resolved_university u
on conflict (university_id, name)
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

with upsert_university as (
  insert into public.universities (name)
  values ('法政大学')
  on conflict (name) do update set name = excluded.name
  returning id
), resolved_university as (
  select id from upsert_university
  union all
  select id from public.universities where name = '法政大学' limit 1
)
insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
select
  u.id,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"09:00","end_time":"10:40"},{"period":2,"label":"2限","start_time":"10:55","end_time":"12:35"},{"period":3,"label":"3限","start_time":"13:20","end_time":"15:00"},{"period":4,"label":"4限","start_time":"15:10","end_time":"16:50"},{"period":5,"label":"5限","start_time":"17:00","end_time":"18:40"}]'::jsonb,
  true
from resolved_university u
on conflict (university_id, name)
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

with upsert_university as (
  insert into public.universities (name)
  values ('中央大学')
  on conflict (name) do update set name = excluded.name
  returning id
), resolved_university as (
  select id from upsert_university
  union all
  select id from public.universities where name = '中央大学' limit 1
)
insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
select
  u.id,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"09:00","end_time":"10:40"},{"period":2,"label":"2限","start_time":"10:55","end_time":"12:35"},{"period":3,"label":"3限","start_time":"13:20","end_time":"15:00"},{"period":4,"label":"4限","start_time":"15:10","end_time":"16:50"},{"period":5,"label":"5限","start_time":"17:00","end_time":"18:40"}]'::jsonb,
  true
from resolved_university u
on conflict (university_id, name)
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

with upsert_university as (
  insert into public.universities (name)
  values ('日本大学')
  on conflict (name) do update set name = excluded.name
  returning id
), resolved_university as (
  select id from upsert_university
  union all
  select id from public.universities where name = '日本大学' limit 1
)
insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
select
  u.id,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"09:00","end_time":"10:40"},{"period":2,"label":"2限","start_time":"10:50","end_time":"12:30"},{"period":3,"label":"3限","start_time":"13:20","end_time":"15:00"},{"period":4,"label":"4限","start_time":"15:10","end_time":"16:50"},{"period":5,"label":"5限","start_time":"17:00","end_time":"18:40"}]'::jsonb,
  true
from resolved_university u
on conflict (university_id, name)
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

with upsert_university as (
  insert into public.universities (name)
  values ('青山学院大学')
  on conflict (name) do update set name = excluded.name
  returning id
), resolved_university as (
  select id from upsert_university
  union all
  select id from public.universities where name = '青山学院大学' limit 1
)
insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
select
  u.id,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"09:00","end_time":"10:40"},{"period":2,"label":"2限","start_time":"10:50","end_time":"12:30"},{"period":3,"label":"3限","start_time":"13:20","end_time":"15:00"},{"period":4,"label":"4限","start_time":"15:10","end_time":"16:50"},{"period":5,"label":"5限","start_time":"17:00","end_time":"18:40"}]'::jsonb,
  true
from resolved_university u
on conflict (university_id, name)
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

with upsert_university as (
  insert into public.universities (name)
  values ('立教大学')
  on conflict (name) do update set name = excluded.name
  returning id
), resolved_university as (
  select id from upsert_university
  union all
  select id from public.universities where name = '立教大学' limit 1
)
insert into public.timetable_presets (university_id, name, weekdays, periods, is_active)
select
  u.id,
  'default',
  array[1,2,3,4,5]::smallint[],
  '[{"period":1,"label":"1限","start_time":"09:00","end_time":"10:40"},{"period":2,"label":"2限","start_time":"10:50","end_time":"12:30"},{"period":3,"label":"3限","start_time":"13:20","end_time":"15:00"},{"period":4,"label":"4限","start_time":"15:10","end_time":"16:50"},{"period":5,"label":"5限","start_time":"17:00","end_time":"18:40"}]'::jsonb,
  true
from resolved_university u
on conflict (university_id, name)
do update set
  weekdays = excluded.weekdays,
  periods = excluded.periods,
  is_active = true,
  updated_at = now();

